### ISSUE TITLE
Option for the 'to date' field to display for Events

### ISSUE THREAD

**Issue by gyounger** [marcom-unimelb/matrix-controlled-environment#139]
Hi, is it possible to have an option for the 'to date’ displaying for events? 

The library wants to use use the same 'single calendar item' for exhibitions, changing the keyword to exhibition, as exhibitions usually run for several months.  

Also, it would be good to be able to disable the time displaying, although i guess this could be opening hours. This might be problem however as the opening hours at the library change regularly and all events would have to be managed around hours as well.

This event runs 14 July 2016 - 15 January 2017:
![screen shot 2016-07-04 at 10 37 04 am](https://cloud.githubusercontent.com/assets/16639864/16548495/550c1d70-41d3-11e6-86bc-e46c9be56d93.png)

thanks
Gav

**Comment by yevek** [comment]
Hi Gavin, I'll need to look into how we display the long running exhibitions.

To not display the time - simply select the "all day event" and "don't show end date".

![image](https://cloud.githubusercontent.com/assets/1305804/16828533/ed9f7188-49d3-11e6-9cfb-824d398a1fa1.png)

**Comment by gyounger** [comment]
Great thanks very much Yevek

**Comment by gyounger** [comment]
@yevek I tried the 'all day' option but events are still displaying times: 
![screen shot 2016-07-20 at 12 21 54 pm](https://cloud.githubusercontent.com/assets/16639864/16973165/9c687684-4e74-11e6-90f2-59e116b6b2e5.png)

**Comment by yevek** [comment]
Hi @gyounger what is the page URL or asset if for this again?

**Comment by gyounger** [comment]
@yevek page asset appears:
http://library.unimelb.edu.au/#today

Actual item page and asset (#2021740):
http://library.unimelb.edu.au/news-and-events/chronicle-a-glimpse-of-the-16th-century-through-recent-acquisitions-from-the-kerry-stokes-collection

thanks

**Comment by yevek** [comment]
@gyounger - looks like I'm only implemented this on the page template https://cms.unimelb.edu.au/controlled-environment/example/local-calendar-assets and not on the handlebars template yet.

**Comment by gyounger** [comment]
@yevek ok no worries thanks. will live without it for now then. cheers

**Comment by yevek** [comment]
Hi @gyounger Tom has fixed the news and events feed so this all works now, check it out here: http://library.unimelb.edu.au/_recache#today

**Comment by gyounger** [comment]
awesome thanks very much @yevek @tomstringer :)
