### ISSUE TITLE
Link Type 2 required for news items

### ISSUE THREAD

**Issue by tomstringer** [marcom-unimelb/matrix-controlled-environment#14]
News items aren't set to show up in the hamburger menu. However, if a news item gets created as a link type 1 asset, the menu gets confused and suggests that the news landing page has children (i.e. - it has an arrow next to it). 

This means you can't actually select the News page itself (see screenshots below).

![screen shot 2015-09-04 at 3 38 07 pm](https://cloud.githubusercontent.com/assets/924501/9677248/073db948-531b-11e5-8e43-8d77740ac9bb.png)
![screen shot 2015-09-04 at 3 38 23 pm](https://cloud.githubusercontent.com/assets/924501/9677250/07886420-531b-11e5-8518-a7077ca76aca.png)
![screen shot 2015-09-04 at 3 38 30 pm](https://cloud.githubusercontent.com/assets/924501/9677249/0785fb0e-531b-11e5-9eaf-a897e6358a24.png)

When all news items are link type 2, it works as expected:

![screen shot 2015-09-04 at 3 39 31 pm](https://cloud.githubusercontent.com/assets/924501/9677262/464f70c2-531b-11e5-888e-92657937aff8.png)
![screen shot 2015-09-04 at 3 39 49 pm](https://cloud.githubusercontent.com/assets/924501/9677263/4696de4e-531b-11e5-9a17-a90f7162c8af.png)

We may need to force news items to be Type 2?

**Comment by yevek** [comment]
closing this as issue was fixed some time ago
