### ISSUE TITLE
events listing component - changing Presenters to Presenter(s)

### ISSUE THREAD

**Issue by siftnoorsingh** [marcom-unimelb/matrix-controlled-environment#143]
The MLS department required that, in the events listing asset, the Presenters heading at the bottom should be changed to Presenter(s) for all the assets in order to indicate that there may be single or multiple presenters for an event.

**Comment by tomstringer** [comment]
This is also corrected in MCE MkII. See https://matrix-cms.unimelb.edu.au/mce/events/events.unimelb-feed-assets/listing-1

"s" is appended only if more than one presenter.

**Comment by yevek** [comment]
Updated to Presenter(s).
