### ISSUE TITLE
Events Listing component - Option to modify date format, for eg. change "12th" to "12"

### ISSUE THREAD

**Issue by siftnoorsingh** [marcom-unimelb/matrix-controlled-environment#144]
![screen shot 2016-07-14 at 10 42 45 am](https://cloud.githubusercontent.com/assets/13805518/16824526/e46e2088-49af-11e6-963a-91421191b1c0.png)
Currently, the date format in events asset is fixed to be as the one above. The law department requires that there should be an option to modify the date format by removing the  "th" or "rd" mentioned beside the date numerical.

**Comment by yevek** [comment]
Local events details page is also without the 'th' so will change the handlebars template to be consistent.

**Comment by yevek** [comment]
This has been implemented in handlebars v2.
