### ISSUE TITLE
events listing component - "Book now" button placed too low web page

### ISSUE THREAD

**Issue by siftnoorsingh** [marcom-unimelb/matrix-controlled-environment#145]
MLS department requires that the "Book Now" button should be more prominent and placed higher up on the Events asset rather than at its current location at the bottom left corner of the page. 
![screen shot 2016-07-14 at 11 01 56 am](https://cloud.githubusercontent.com/assets/13805518/16824852/71988fdc-49b2-11e6-86c1-8062ac31aa9c.png)

This is not required for the mobile page where the "Book Now" button has been placed at a prominent location.
![screen shot 2016-07-14 at 10 58 26 am](https://cloud.githubusercontent.com/assets/13805518/16824844/571f3b38-49b2-11e6-93aa-cd23a7daa621.png)

**Comment by yevek** [comment]
Yes I think this would look better if the book now button was moved above the address. Will just check withe the design team first.

**Comment by yevek** [comment]
Moved the book now button to top of aside content.
