### ISSUE TITLE
Show more option not displayed

### ISSUE THREAD

**Issue by namgupta** [marcom-unimelb/matrix-controlled-environment#153]
When i tried using a tag to filter events and the output should have shown 15 events followed by a Show More button, it doesn't show the button.

Having the same filter with news feed, however displays the show more button.

eg. http://law.unimelb.edu.au/centres/research-centre-events/

**Comment by angehb** [comment]
Just wondering when this bug will be looked as the purpose of the page is for 'Events' only.  We don't wish to display 'News' on this page.

**Comment by yevek** [comment]
Hi @angehb we will be rolling out a change this week that will fix the issue of tagging for events. We are in the final stages of testing.

**Comment by namgupta** [comment]
New issue, on filtering events with multiple tags -ALC,CCCS,CELRL,CCLSR,CILIS,CMCL,CLEN,CREEL,CJRG,ERRN,GELN,IILAH,OG,Tax Group,Transactional Law

There are some events which are displayed twice, which might be because of multiple of the above tags being assigned to an event.

Attaching screenshots.
<img width="1434" alt="screen shot 2016-09-05 at 3 59 32 pm" src="https://cloud.githubusercontent.com/assets/19420313/18259765/04a51d8e-742b-11e6-8760-e4ce427e9756.png">
<img width="1322" alt="screen shot 2016-09-06 at 12 06 03 pm" src="https://cloud.githubusercontent.com/assets/19420313/18259766/0515d51a-742b-11e6-8bf8-f31e507bb42a.png">

**Comment by tomstringer** [comment]
Resolved via release of combined listing v3.
