### ISSUE TITLE
Centering Image Gallery with limited images

### ISSUE THREAD

**Issue by gyounger** [marcom-unimelb/matrix-controlled-environment#158]
Hi, see example:

Before:
![screen shot 2016-08-18 at 4 57 07 pm](https://cloud.githubusercontent.com/assets/16639864/17764773/ea99e098-6564-11e6-81ce-9fd980883d48.png)

Via https://cms.unimelb.edu.au/controlled-environment/tuc/objects/percy-grainger-by-rupert-bunny/_recache

This has been centered with a class, but it shrinks the gallery and spacing is the best. 

After:
![screen shot 2016-08-18 at 4 58 18 pm](https://cloud.githubusercontent.com/assets/16639864/17764794/01ae3f7c-6565-11e6-9ab0-7314c03d0a27.png)

Not all the galleries on this site will have limited, i.e. 2, images but there are some that will.

thanks
Gav

**Comment by yevek** [comment]
Hi @gyounger I think this is also a Design Issue and should be logged here: https://github.com/marcom-unimelb/unimelb-design-system/issues

**Comment by gyounger** [comment]
@yevek no worries, done
