### ISSUE TITLE
Singular events do not display meta title correctly

### ISSUE THREAD

**Issue by rothenburycam** [marcom-unimelb/matrix-controlled-environment#162]
On single calendar events pages, the meta title is displayed as the URL, not the name of the asset.

![screen shot 2016-08-22 at 3 49 51 pm](https://cloud.githubusercontent.com/assets/11714609/17844751/1b956fa0-6880-11e6-8833-0d376a34d919.png)

**Comment by yevek** [comment]
Hi Camryn, looks like the metadata schemas on the events here need to be regenerated - you can manually do this by going to the metadata screen and deselecting "use default" then reselecting on "page title" field and saving. You could probably also do this via the parent asset and cascade the changes. 

http://library.unimelb.edu.au/research/researcher@library-week/program/openness-and-innovation-in-scholarly-communication-the-future-is-now

<img width="830" alt="page-title" src="https://cloud.githubusercontent.com/assets/1305804/17845221/9c60a084-6883-11e6-8b94-f3d6f298a42d.png">

**Comment by rothenburycam** [comment]
Brilliant. Thanks @yevek - that worked perfectly with cascade.

Cheers!
