### ISSUE TITLE
Flash announcement appearing w added padding on Library homepage

### ISSUE THREAD

**Issue by gyounger** [marcom-unimelb/matrix-controlled-environment#163]
Hi, I tried to add a flash announcement to the Library homepage but it's appearing with 100px padding top:
![screen shot 2016-08-29 at 2 29 06 pm](https://cloud.githubusercontent.com/assets/16639864/18040784/0742715e-6df5-11e6-9ffa-111f547a4cc8.png)

thanks
Gav

**Comment by yevek** [comment]
Hi @gyounger this needs to go onto https://github.com/marcom-unimelb/unimelb-design-system/issues

**Comment by gyounger** [comment]
@yevek whoops yes, thanks, that kinda day
