### ISSUE TITLE
Remove st, nd, rd, th from events in combined listing and content template

### ISSUE THREAD

**Issue by yevek** [marcom-unimelb/matrix-controlled-environment#206]
Requested from Naman on http://law.unimelb.edu.au/events
---------
For consistency with design system we should remove st, nd, rd, th from events http://web.unimelb.edu.au/components/listings on both 

- news events component
  https://resources.web.unimelb.edu.au/controlled-environment/content-templates/news-events 
- combined news listing

![image](https://cloud.githubusercontent.com/assets/1305804/19876625/ec56e8fc-a02b-11e6-8218-e81894984a98.png)

**Comment by tomstringer** [comment]
Fixed with https://github.com/marcom-unimelb/matrix-controlled-environment/commit/58ec074e044671d9a179074ebee13c0427120e40

**Comment by tomstringer** [comment]
Actually - re-opening. Combined news/events listing has been fixed. Needs to be updated in Content Template.

**Comment by tomstringer** [comment]
Ok. _Now_ it's fixed.
