### ISSUE TITLE
Components Checklist "tick" not showing (no ::after pseudo element)

### ISSUE THREAD

**Issue by jporich** [marcom-unimelb/matrix-controlled-environment#207]
Component works as intended, however checkbox "tick" does not appear as visible (see screen shot attached).

Issue may stem from no ::after element being applied from javascript(?)

https://cms.unimelb.edu.au/controlled-environment/mgse/contact-us

Copied and pasted example from http://web.unimelb.edu.au/components/checklist/
<img width="1440" alt="no check" src="https://cloud.githubusercontent.com/assets/10070570/19879396/45fab0e0-a046-11e6-8e50-4bcc6197498e.png">

**Comment by yevek** [comment]
@jporich you should be using this content template 
https://resources.web.unimelb.edu.au/controlled-environment/content-templates/checklist

**Comment by yevek** [comment]
closing this as content template in MCE works.
