### ISSUE TITLE
News Items enhancement ( Details / Related Link / URL ) - quasi redirect feature 

### ISSUE THREAD

**Issue by cigar69** [marcom-unimelb/matrix-controlled-environment#211]
The MDHS Marketing & Communications is seeking a solution to reduce the effort of duplication from the existing three platforms. 

1. http://theconversation.com/au/
2. http://newsroom.melbourne.edu/
3. https://pursuit.unimelb.edu.au/

Currently the research driven Faculty Of MDHS provides each of its 31 Departments their very own news & events feeds. This vibrant community is then provided the option to promote their news to the School's and/or Faculty's news feed ( build it once show everywhere).

At the moment the Matrix News Item template displays a Realted Link field in which to populate
![capture](https://cloud.githubusercontent.com/assets/4565925/20252989/338c4c7c-aa7b-11e6-8040-ec2eaa8cd6ec.JPG)

On first glance it appears that a URL could be inserted to point the user to either a internal or external site ( where the original article is published).

It would be worth investigating for this feature to be made available to authors to reduce the MDHS Comms duplication effort down to just Title & Teaser text and Redirect link.

This solution would still allow for Department stories to promoted higher up the organizational structure.

**Comment by tomstringer** [comment]
Hi Brendan

I don't fully understand what you're after here. Are you essentially wanting to be able to use News Items as redirects to other platforms (Pursuit, Newsroom etc)?

So if the Related Link URL field is populated, it uses that link when a user clicks on it, rather than the link to the News Item itself?

**Comment by cigar69** [comment]
BIG FAT YES to both questions

**Comment by tomstringer** [comment]
So this should be possible using the %link_url%  keyword conditionally (ie - if %link_url%  populated, use it, otherwise use %asset_url%). 

The only hesitation is whether or not other people are using that field for some other purpose that we don't know about.

@yevek Any thoughts?

**Comment by yevek** [comment]
@tomstringer I would suggest using the actual "link asset" instead of the news asset so that we could use the fields correctly. Would avoid any confusion by users and reduce any potential future risks.

**Comment by cigar69** [comment]
@yevek @tomstringer 

1. Will that mean Links assets created under the News & Events will need to applied with a news item paintlayout?

2. That our news promotion tool and triggers will need to be re-jigged to ensure Link assets can be promoted higher up the organizational structure ( like News Item currently)?

**Comment by yevek** [comment]
that's all the stuff that we need to work out @cigar69 but that is the end goal.

**Comment by cigar69** [comment]
Just flagging this again so it doesn't fall off the radar

**Comment by cigar69** [comment]
just flagging this again so it doesn't fall off the radar

**Comment by yevek** [comment]
@cigar69 I'll take a look at this today Brendan, can you please give me some URLs to sites where you want to use this?

**Comment by cigar69** [comment]
The enhancement should be available to be used across all our news pages (if required).

Are you asking for examples of a pursuit news items that we then had duplicated in Matrix?

**Comment by yevek** [comment]
we have over 138 websites in MCE now, I'm asking if you can provide some links to the pages where you want the news items to end up please. It will save me spending some time trying to figure out where your news pages are.

**Comment by cigar69** [comment]
**Faculty**

http://mdhs.unimelb.edu.au/news-and-events

**Schools**

http://medicine.unimelb.edu.au/news-and-events
http://dental.unimelb.edu.au/news-and-events
http://healthsciences.unimelb.edu.au/news-and-events
http://mspgh.unimelb.edu.au/news-and-events
http://psychologicalsciences.unimelb.edu.au/news-and-events
http://biomedicalsciences.unimelb.edu.au/news-and-events

**Some Departments in SBS **

biomedicalsciences.unimelb.edu.au/departments/anatomy-and-neuroscience/news-and-events
http://biomedicalsciences.unimelb.edu.au/departments/biochemistry/news-and-events
biomedicalsciences.unimelb.edu.au/departments/microbiology-Immunology/news-and-events
biomedicalsciences.unimelb.edu.au/departments/pathology/news-and-events
biomedicalsciences.unimelb.edu.au/departments/pharmacology/news-and-events
biomedicalsciences.unimelb.edu.au/departments/physiology/news-and-events

**Comment by yevek** [comment]
Hi Brendan, you can now use the "link asset" to add single articles to your site. This is still a form of duplication but at least your editors don't have to republish the entire article. 

I've added instructions on this page: https://resources.web.unimelb.edu.au/controlled-environment/help-guides/v3-combined-listing-help under FAQ's called "How do I link to a single article on another site?"

I'll close this ticket off now.
