### ISSUE TITLE
Figure out tags in events and news

### ISSUE THREAD

**Issue by tomstringer** [marcom-unimelb/matrix-controlled-environment#4]
Work out a way to create and manage tags for local news and events.

**Comment by yevek** [comment]
Using the metadata "keyword" field we can tag news and events and this will appear in various news and events listings https://cms.unimelb.edu.au/controlled-environment/example/news-and-events-local/demo/keywords-now-in-use

The next thing is to do some sort of filtering/sorting by tags - will need to work with the design team on this however.

**Comment by yevek** [comment]
Asialink want to display stories according to tag. 

![news-tagging](https://cloud.githubusercontent.com/assets/1305804/17238740/999f0bd2-55a1-11e6-8651-0af50bace2d1.png)

**Comment by yevek** [comment]
Have logged this one on https://github.com/marcom-unimelb/unimelb-design-system/issues/772 for Design Team to look at
