### ISSUE TITLE
Multi day event not showing end date - Issue with the Events feed

### ISSUE THREAD

**Issue by yevek** [marcom-unimelb/matrix-controlled-environment#93]
From Giles in Science. 

There is an event currently feeding through from events.unimelb.edu.au which is a multi day event, but the output through does not reflect the end date.

Its this event:  http://science.unimelb.edu.au/events/details?event=6106
The original event is here:  http://events.unimelb.edu.au/events/6106-uom-at-melbourne-international-flower-and-garden-show

We'd like the events feed to be able to show the end date of multi day events.

![multidate-event-feed](https://cloud.githubusercontent.com/assets/1305804/15131230/87001fb0-1691-11e6-9a74-35c5ed5bcabc.png)

![calendar-single-date](https://cloud.githubusercontent.com/assets/1305804/15131244/ae6661ae-1691-11e6-8f48-afffe8202abd.png)

**Comment by siftnoorsingh** [comment]
The Law department requires this as well. And they would like it to be a part of the component itself rather than having to hardcode it in, as there are content owners here who do not have knowledge of HTML.

**Comment by tomstringer** [comment]
I'm building this in MCE MkII - we should be able to roll it into MCE 1 once it's fully tested.

**Comment by yevek** [comment]
Multicalendar dates now appearing in feed from events.unimelb - in process of rolling out across current usage in MCE. See working example here: http://arts.unimelb.edu.au/#news-events
